### PR TITLE
Updating generic views

### PR DESCRIPTION
**Pull request by andrewhayward**
Adding `HybridListView` and `HybridDetailView`, which work much like the standard `ListView` and `DetailView` but are able to serve additional content types depending on the request.

``` python
# views.py
from mozbadges.views.generic.detail import HybridDetailView

class ModelDetailView(HybridDetailView):
    model = Model

model_detail = ModelDetailView.as_view()
```

``` python
# urls.py
url(r'^.../model(?:/|.json|.xml)$', views.model_detail)
```

Also moved `placeholder_view` from `mozbadges.utils.views` to `mozbadges.views` - at some point we can kill it entirely.

### CODE REVIEW

**Comment by andrewhayward** [comment]
@christensenep Can you sanity check this?

**Comment by ghost** [comment]
Cool, I like that.  Looks good.

**Comment by andrewhayward** [comment]
Worth noting that it doesn't actually support xml right now, but the point is that it would be easy enough to add should we want to do that.

Anyway, I'm gonna merge.

**Comment by ghost** [comment]
Yeah, I did indeed notice that, but we can add as needed.

**Pull request merged**
